services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: finopal
      MYSQL_USER: finopal
      MYSQL_PASSWORD: finopal
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - finopal_mysql:/var/lib/mysql
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  finopal_mysql:
